# Generated by Django 5.2.7 on 2025-12-30 05:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('otp_token', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_category', models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('service_payment', 'Service Payment'), ('beneficiary_verification', 'Beneficiary Verification'), ('other', 'Other')], max_length=30, unique=True)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=10)),
                ('charge_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('master', 'Master'), ('dealer', 'Dealer'), ('retailer', 'Retailer')], default='retailer', max_length=20)),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('has_completed_first_time_setup', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_nature', models.CharField(blank=True, choices=[('retail_shop', 'Retail Shop'), ('wholesale', 'Wholesale'), ('service_provider', 'Service Provider'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('franchise', 'Franchise'), ('other', 'Other')], max_length=50, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('business_ownership_type', models.CharField(blank=True, choices=[('private', 'Private'), ('private_limited', 'Private Limited'), ('llc', 'Limited Liability Company (LLC)'), ('public_limited', 'Public Limited'), ('other', 'Other')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_card', models.CharField(blank=True, max_length=500, null=True)),
                ('aadhar_card', models.CharField(blank=True, max_length=500, null=True)),
                ('passport_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('shop_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('store_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('other_documents', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForgetPinOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='users.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserService', to='services.servicesubcategory'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pin_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_pin_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletPinOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('set_pin', 'Set PIN'), ('reset_pin', 'Reset PIN')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cash_deposit', 'Cash Deposit'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('deposit_bank', models.CharField(choices=[('State Bank of India', 'State Bank of India'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('Axis Bank', 'Axis Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Canara Bank', 'Canara Bank'), ('Union Bank of India', 'Union Bank of India'), ('Indian Bank', 'Indian Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('IDFC FIRST Bank', 'IDFC FIRST Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Central Bank of India', 'Central Bank of India'), ('Bank of India', 'Bank of India'), ('UCO Bank', 'UCO Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Yes Bank', 'Yes Bank'), ('Federal Bank', 'Federal Bank'), ('South Indian Bank', 'South Indian Bank'), ('RBL Bank', 'RBL Bank'), ('IDBI Bank', 'IDBI Bank'), ('Jammu & Kashmir Bank', 'Jammu & Kashmir Bank'), ('Karnataka Bank', 'Karnataka Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank')], max_length=300)),
                ('Your_Bank', models.CharField(choices=[('State Bank of India', 'State Bank of India'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('Axis Bank', 'Axis Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Canara Bank', 'Canara Bank'), ('Union Bank of India', 'Union Bank of India'), ('Indian Bank', 'Indian Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('IDFC FIRST Bank', 'IDFC FIRST Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Central Bank of India', 'Central Bank of India'), ('Bank of India', 'Bank of India'), ('UCO Bank', 'UCO Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Yes Bank', 'Yes Bank'), ('Federal Bank', 'Federal Bank'), ('South Indian Bank', 'South Indian Bank'), ('RBL Bank', 'RBL Bank'), ('IDBI Bank', 'IDBI Bank'), ('Jammu & Kashmir Bank', 'Jammu & Kashmir Bank'), ('Karnataka Bank', 'Karnataka Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank')], max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='fund_requests/screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fund_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_fundr_status_06fb1b_idx'), models.Index(fields=['user', 'created_at'], name='users_fundr_user_id_7b2de8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
                'indexes': [models.Index(fields=['user', 'set_at'], name='users_pinhi_user_id_01ccd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('master', 'Master'), ('dealer', 'Dealer'), ('retailer', 'Retailer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('transaction_category', models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('service_payment', 'Service Payment'), ('beneficiary_verification', 'Beneficiary Verification'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='success', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('service_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='services.servicesubmission')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='users_trans_wallet__95572f_idx'), models.Index(fields=['transaction_type', 'status'], name='users_trans_transac_62a91d_idx'), models.Index(fields=['transaction_category', 'created_at'], name='users_trans_transac_a9f642_idx'), models.Index(fields=['reference_number'], name='users_trans_referen_efec7b_idx'), models.Index(fields=['service_submission'], name='users_trans_service_d018e6_idx')],
            },
        ),
    ]
