# Generated by Django 5.2.7 on 2026-01-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='wallet_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
