# Generated by Django 5.2.7 on 2026-01-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fundrequest_service_charge_fundrequest_wallet_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='Your_Bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='deposit_bank',
            field=models.CharField(max_length=300),
        ),
    ]
