# Generated by Django 5.2.7 on 2026-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fundrequest_your_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='provider',
            field=models.CharField(blank=True, default='database', max_length=20),
        ),
    ]
