# Generated by Django 5.2.7 on 2025-10-29 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicecategory_require_browse_plan_and_more'),
        ('users', '0005_state_user_aadhar_card_user_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory'),
        ),
    ]
