# Generated by Django 5.2.7 on 2026-01-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
