# Generated by Django 5.2.7 on 2025-10-30 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cash_deposit', 'Cash Deposit'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='fund_requests/screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fund_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_fundr_status_06fb1b_idx'), models.Index(fields=['user', 'created_at'], name='users_fundr_user_id_7b2de8_idx')],
            },
        ),
    ]
