# Generated by Django 5.2.7 on 2025-10-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fundrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='Your_Bank',
            field=models.CharField(choices=[('State Bank of India', 'State Bank of India'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('Axis Bank', 'Axis Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Canara Bank', 'Canara Bank'), ('Union Bank of India', 'Union Bank of India'), ('Indian Bank', 'Indian Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('IDFC FIRST Bank', 'IDFC FIRST Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Central Bank of India', 'Central Bank of India'), ('Bank of India', 'Bank of India'), ('UCO Bank', 'UCO Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Yes Bank', 'Yes Bank'), ('Federal Bank', 'Federal Bank'), ('South Indian Bank', 'South Indian Bank'), ('RBL Bank', 'RBL Bank'), ('IDBI Bank', 'IDBI Bank'), ('Jammu & Kashmir Bank', 'Jammu & Kashmir Bank'), ('Karnataka Bank', 'Karnataka Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='deposit_bank',
            field=models.CharField(choices=[('State Bank of India', 'State Bank of India'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('Axis Bank', 'Axis Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Canara Bank', 'Canara Bank'), ('Union Bank of India', 'Union Bank of India'), ('Indian Bank', 'Indian Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('IDFC FIRST Bank', 'IDFC FIRST Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Central Bank of India', 'Central Bank of India'), ('Bank of India', 'Bank of India'), ('UCO Bank', 'UCO Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Yes Bank', 'Yes Bank'), ('Federal Bank', 'Federal Bank'), ('South Indian Bank', 'South Indian Bank'), ('RBL Bank', 'RBL Bank'), ('IDBI Bank', 'IDBI Bank'), ('Jammu & Kashmir Bank', 'Jammu & Kashmir Bank'), ('Karnataka Bank', 'Karnataka Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
