# Generated by Django 5.2.7 on 2026-01-15 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_city_district_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
