# Generated by Django 5.2.7 on 2026-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_uid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
