# Generated by Django 5.2.7 on 2025-10-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_fundrequest_bank_name_fundrequest_your_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_request',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.fundrequest'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', ' Admin'), ('master', 'Master'), ('dealer', 'Dealer'), ('retailer', 'Retailer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', ' Admin'), ('master', 'Master'), ('dealer', 'Dealer'), ('retailer', 'Retailer')], default='retailer', max_length=20),
        ),
        migrations.DeleteModel(
            name='BalanceRequest',
        ),
    ]
