# Generated by Django 5.2.7 on 2026-01-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('requested', 'Refund Requested'), ('approved', 'Refund Approved'), ('processed', 'Refund Processed')], default='none', max_length=20),
        ),
    ]
