# Generated by Django 5.2.7 on 2025-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_transaction_balance_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fund_request',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('master', 'Master'), ('dealer', 'Dealer'), ('retailer', 'Retailer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('master', 'Master'), ('dealer', 'Dealer'), ('retailer', 'Retailer')], default='retailer', max_length=20),
        ),
    ]
