# Generated by Django 5.2.7 on 2026-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_transaction_refund_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='success', max_length=10),
        ),
    ]
