# Generated by Django 5.2.7 on 2025-10-31 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_transaction_fund_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_category', models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('other', 'Other')], max_length=20, unique=True)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=10)),
                ('charge_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='success', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='users_trans_wallet__95572f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='users_trans_transac_62a91d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_category', 'created_at'], name='users_trans_transac_a9f642_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='users_trans_referen_efec7b_idx'),
        ),
    ]
