# Generated by Django 5.2.7 on 2026-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fundrequest_txn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UTR / Bank Reference Number provided by user', max_length=100, null=True),
        ),
    ]
