# Generated by Django 5.2.7 on 2026-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_fundrequest_utr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_passwordless_login',
            field=models.BooleanField(default=False),
        ),
    ]
