# Generated by Django 5.2.7 on 2026-01-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_transaction_eko_client_ref_id_transaction_eko_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='eko_client_ref_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='eko_tid',
        ),
    ]
