# Generated by Django 5.2.7 on 2025-10-31 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicecategory_require_browse_plan_and_more'),
        ('users', '0011_servicecharge_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPinOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('set_pin', 'Set PIN'), ('reset_pin', 'Reset PIN')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='services.servicesubmission'),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='transaction_category',
            field=models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('service_payment', 'Service Payment'), ('other', 'Other')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('service_payment', 'Service Payment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['service_submission'], name='users_trans_service_d018e6_idx'),
        ),
        migrations.AddField(
            model_name='walletpinotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
