# Generated by Django 5.2.7 on 2026-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_allow_passwordless_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_passwordless_login',
            field=models.BooleanField(default=True),
        ),
    ]
