# Generated by Django 5.2.7 on 2025-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_walletpinotp_transaction_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_first_time_setup',
            field=models.BooleanField(default=False),
        ),
    ]
