# Generated by Django 5.2.7 on 2026-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_allow_passwordless_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_status',
            field=models.CharField(default='not_refunded', max_length=20),
        ),
    ]
