# Generated by Django 5.2.7 on 2026-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_transaction_eko_client_ref_id_transaction_eko_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='txn_date',
            field=models.DateTimeField(blank=True, help_text='Transaction / Deposit Date provided by user', null=True),
        ),
    ]
