# Generated by Django 5.2.7 on 2026-02-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_transaction_refund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='refund_status',
        ),
    ]
