# Generated by Django 5.2.7 on 2026-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
