# Generated by Django 5.2.7 on 2025-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_mobileotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
