# Generated by Django 5.2.7 on 2025-12-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_transaction_closing_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
                'indexes': [models.Index(fields=['user', 'set_at'], name='users_pinhi_user_id_01ccd0_idx')],
            },
        ),
    ]
