# Generated by Django 5.2.7 on 2025-12-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pinhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='transaction_category',
            field=models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('service_payment', 'Service Payment'), ('beneficiary_verification', 'Beneficiary Verification'), ('other', 'Other')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('fund_request', 'Fund Request'), ('money_transfer', 'Money Transfer'), ('bill_payment', 'Bill Payment'), ('bbps', 'bbps'), ('service_charge', 'Service Charge'), ('cashback', 'Cashback'), ('refund', 'Refund'), ('commission', 'Commission'), ('service_payment', 'Service Payment'), ('beneficiary_verification', 'Beneficiary Verification'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
