# Generated by Django 5.2.7 on 2025-12-30 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbps', '0002_initial'),
        ('commission', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='commission_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.commissionplan'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='main_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_transactions', to='users.transaction'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='retailer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='service_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubmission'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorcommission',
            name='commission_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.commissionplan'),
        ),
        migrations.AddField(
            model_name='operatorcommission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorcommission',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='bbps.operator'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='operator_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commission.operatorcommission'),
        ),
        migrations.AddField(
            model_name='servicecommission',
            name='commission_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.commissionplan'),
        ),
        migrations.AddField(
            model_name='servicecommission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecommission',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicecommission',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='commission_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commission.servicecommission'),
        ),
        migrations.AddField(
            model_name='usercommissionplan',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercommissionplan',
            name='commission_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.commissionplan'),
        ),
        migrations.AddField(
            model_name='usercommissionplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='operatorcommission',
            unique_together={('operator', 'commission_plan', 'operator_circle')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecommission',
            unique_together={('service_subcategory', 'commission_plan')},
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['user', 'created_at'], name='commission__user_id_4500dd_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['retailer_user', 'created_at'], name='commission__retaile_784685_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['status', 'created_at'], name='commission__status_ad6057_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['role', 'created_at'], name='commission__role_8264cd_idx'),
        ),
    ]
