# Generated by Django 5.2.7 on 2026-01-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionplan',
            name='plan_type',
            field=models.CharField(help_text='Unique key like platinum, gold, diamond, premium', max_length=50, unique=True),
        ),
    ]
