# Generated by Django 5.2.7 on 2026-01-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_alter_commissionplan_plan_type'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorcommission',
            name='service_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operator_commissions', to='services.servicesubcategory'),
            preserve_default=False,
        ),
    ]
