# Generated by Django 5.2.7 on 2026-01-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0004_operatorcommission_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorcommission',
            name='service_subcategory',
        ),
    ]
