# Generated by Django 5.2.7 on 2026-01-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbps', '0002_initial'),
        ('commission', '0005_remove_operatorcommission_service_subcategory'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatorcommission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='operatorcommission',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_commissions', to='services.servicesubcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorcommission',
            unique_together={('operator', 'service_subcategory', 'commission_plan', 'operator_circle')},
        ),
    ]
