# Generated by Django 5.2.7 on 2026-01-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_alter_operatorcommission_unique_together_and_more'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorcommission',
            name='service_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_commissions', to='services.servicesubcategory'),
        ),
    ]
