# Generated by Django 5.2.7 on 2026-01-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_alter_operatorcommission_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorcommission',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='operatorcommission',
            name='min_amount',
        ),
    ]
