# Generated by Django 5.2.7 on 2026-01-24 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_remove_operatorcommission_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorcommission',
            name='max_commission_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum commission allowed (from CSV, cannot be exceeded)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
