# Generated by Django 5.2.7 on 2025-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=14)),
                ('pan_no', models.CharField(blank=True, max_length=10)),
                ('admin', models.BooleanField(default=False)),
                ('superadmin', models.BooleanField(default=False)),
                ('master', models.BooleanField(default=False)),
                ('dealer', models.BooleanField(default=False)),
                ('retailer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
