# Generated by Django 5.2.7 on 2025-10-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategory',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
