# Generated by Django 5.2.7 on 2025-10-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicesubmission_submitted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Service Sub Categories'},
        ),
    ]
