# Generated by Django 5.2.7 on 2025-10-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicesubcategory_require_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='allow_direct_service',
            field=models.BooleanField(default=False),
        ),
    ]
