# Generated by Django 5.2.7 on 2025-10-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicecategory_require_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='require_browse_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_fetch_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_plan_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_browse_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_fetch_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_plan_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('email', 'Email Input'), ('phone', 'Phone Input'), ('textarea', 'Text Area'), ('boolean', 'Checkbox'), ('select', 'Dropdown'), ('multiselect', 'Multiple Select'), ('date', 'Date Picker'), ('file', 'File Upload'), ('radio', 'Radio Buttons'), ('amount', 'Amount'), ('operator', 'Operator'), ('circle', 'Circle'), ('plan_type', 'Plan Type'), ('bbps_type', 'bbps Type'), ('button', 'Button'), ('plan_browse', 'Browse Plans'), ('plan_fetch', 'Fetch Plans'), ('plan_selection', 'Plan Selection')], max_length=20),
        ),
    ]
