# Generated by Django 5.2.7 on 2025-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicecategory_require_browse_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFetchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('electricity', 'Electricity Bill'), ('water', 'Water Bill'), ('gas', 'Gas Bill'), ('broadband', 'Broadband Bill'), ('loan_emi', 'Loan EMI'), ('fastag', 'Fastag bbps'), ('credit_card', 'Credit Card Bill'), ('society_maintenance', 'Society Maintenance'), ('traffic_challan', 'Traffic Challan'), ('education_fee', 'Education Fee'), ('rent', 'Rent Payment'), ('dth', 'DTH bbps'), ('mobile', 'Mobile bbps')], max_length=50, unique=True)),
                ('identifier_field', models.CharField(help_text='Field name used to fetch bill', max_length=100)),
                ('identifier_label', models.CharField(help_text='Label for identifier field', max_length=100)),
                ('fetch_endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
