# Generated by Django 5.2.7 on 2025-11-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_billfetchconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='require_adhar_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_branch_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_broadband_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_confirm_account_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_flat_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_ifsc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_landline_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_upi_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='require_water_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_adhar_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_branch_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_broadband_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_confirm_account_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_flat_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_ifsc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_landline_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_upi_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='require_water_board',
            field=models.BooleanField(default=False),
        ),
    ]
