# Generated by Django 5.2.7 on 2025-11-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMTServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_range', models.CharField(choices=[('0-1000', '₹0 - ₹1,000'), ('1001-10000', '₹1,001 - ₹10,000'), ('10001-25000', '₹10,001 - ₹25,000'), ('25001-50000', '₹25,001 - ₹50,000'), ('50001-100000', '₹50,001 - ₹1,00,000')], max_length=20, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='DMTBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.IntegerField(unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bank_name'],
                'indexes': [models.Index(fields=['bank_name'], name='dmt_dmtbank_bank_na_6dd0b6_idx'), models.Index(fields=['is_active'], name='dmt_dmtbank_is_acti_689887_idx')],
            },
        ),
        migrations.CreateModel(
            name='DMTRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('confirm_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('account_type', models.IntegerField(choices=[(1, 'Savings Account'), (2, 'Current Account'), (3, 'Salary Account')], default=1)),
                ('recipient_type', models.IntegerField(choices=[(1, 'Individual'), (2, 'Corporate'), (3, 'Other')], default=1)),
                ('eko_recipient_id', models.IntegerField(blank=True, null=True)),
                ('eko_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_response', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DMTSenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_method', models.CharField(blank=True, choices=[('biometric', 'Biometric'), ('otp', 'OTP'), ('manual', 'Manual')], max_length=20, null=True)),
                ('eko_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_profile_data', models.JSONField(blank=True, null=True)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=200000.0, max_digits=10)),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('daily_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_sender_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DMTTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('imps', 'IMPS'), ('neft', 'NEFT'), ('rtgs', 'RTGS')], default='imps', max_length=10)),
                ('sender_mobile', models.CharField(max_length=15)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_account', models.CharField(max_length=50)),
                ('recipient_ifsc', models.CharField(max_length=11)),
                ('recipient_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('eko_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_recipient_id', models.IntegerField(blank=True, null=True)),
                ('eko_otp_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_kyc_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('otp_sent', 'OTP Sent'), ('verified', 'OTP Verified'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dmt.dmtrecipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dmtrecipient',
            index=models.Index(fields=['recipient_id'], name='dmt_dmtreci_recipie_518099_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtrecipient',
            index=models.Index(fields=['user', 'is_active'], name='dmt_dmtreci_user_id_0e069b_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtrecipient',
            index=models.Index(fields=['eko_recipient_id'], name='dmt_dmtreci_eko_rec_b88e4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dmtrecipient',
            unique_together={('user', 'account_number', 'ifsc_code')},
        ),
        migrations.AddIndex(
            model_name='dmtsenderprofile',
            index=models.Index(fields=['mobile'], name='dmt_dmtsend_mobile_e00412_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtsenderprofile',
            index=models.Index(fields=['kyc_status'], name='dmt_dmtsend_kyc_sta_8dde6f_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtsenderprofile',
            index=models.Index(fields=['eko_customer_id'], name='dmt_dmtsend_eko_cus_e1f573_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['transaction_id'], name='dmt_dmttran_transac_6d4829_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['user', 'initiated_at'], name='dmt_dmttran_user_id_658085_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['status', 'initiated_at'], name='dmt_dmttran_status_d978f3_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['sender_mobile'], name='dmt_dmttran_sender__236384_idx'),
        ),
    ]
