# Generated by Django 5.2.7 on 2025-12-30 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dmtsenderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_sender_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dmt.dmtrecipient'),
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dmttransactioncharge',
            name='charge_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmt.dmtchargescheme'),
        ),
        migrations.AddField(
            model_name='dmttransactioncharge',
            name='dmt_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_details', to='dmt.dmttransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='dmtchargescheme',
            unique_together={('plan', 'amount_from', 'amount_to')},
        ),
        migrations.AddIndex(
            model_name='dmtrecipient',
            index=models.Index(fields=['recipient_id'], name='dmt_dmtreci_recipie_518099_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtrecipient',
            index=models.Index(fields=['user', 'is_active'], name='dmt_dmtreci_user_id_0e069b_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtrecipient',
            index=models.Index(fields=['eko_recipient_id'], name='dmt_dmtreci_eko_rec_b88e4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dmtrecipient',
            unique_together={('user', 'account_number', 'ifsc_code')},
        ),
        migrations.AddIndex(
            model_name='dmtsenderprofile',
            index=models.Index(fields=['mobile'], name='dmt_dmtsend_mobile_e00412_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtsenderprofile',
            index=models.Index(fields=['kyc_status'], name='dmt_dmtsend_kyc_sta_8dde6f_idx'),
        ),
        migrations.AddIndex(
            model_name='dmtsenderprofile',
            index=models.Index(fields=['eko_customer_id'], name='dmt_dmtsend_eko_cus_e1f573_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['transaction_id'], name='dmt_dmttran_transac_6d4829_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['user', 'initiated_at'], name='dmt_dmttran_user_id_658085_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['status', 'initiated_at'], name='dmt_dmttran_status_d978f3_idx'),
        ),
        migrations.AddIndex(
            model_name='dmttransaction',
            index=models.Index(fields=['sender_mobile'], name='dmt_dmttran_sender__236384_idx'),
        ),
    ]
