# Generated by Django 5.2.7 on 2025-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkoBank',
            fields=[
                ('bank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=50)),
                ('imps_status', models.CharField(max_length=50)),
                ('neft_status', models.CharField(max_length=50)),
                ('verification_status', models.CharField(max_length=50)),
                ('ifsc_status', models.CharField(max_length=255)),
                ('static_ifsc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='client_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='eko_bank_ref_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='eko_tid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='eko_tx_status',
            field=models.CharField(blank=True, choices=[('0', 'Success'), ('1', 'Fail'), ('2', 'Response Awaited/Initiated'), ('3', 'Refund Pending'), ('4', 'Refunded'), ('5', 'Hold (Transaction Inquiry Required)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dmttransaction',
            name='eko_txstatus_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
