# Generated by Django 5.2.7 on 2026-01-30 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dmtrecipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dmtrecipient',
            name='customer_mobile',
            field=models.CharField(db_index=True, default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dmtrecipient',
            name='is_bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dmtrecipient',
            name='verification_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='dmtrecipient',
            unique_together={('customer_mobile', 'account_number')},
        ),
    ]
