# Generated by Django 5.2.7 on 2025-12-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0002_ekobank_dmttransaction_client_ref_id_and_more'),
        ('users', '0017_mobileotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmttransaction',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmt_transaction', to='users.transaction'),
        ),
    ]
