# Generated by Django 5.2.7 on 2025-12-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0003_dmttransaction_wallet_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmttransaction',
            name='wallet_transaction',
        ),
    ]
