# Generated by Django 5.2.7 on 2026-02-02 05:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0003_alter_dmtrecipient_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dmtrecipient',
            unique_together={('user', 'account_number', 'ifsc_code')},
        ),
        migrations.RemoveField(
            model_name='dmtrecipient',
            name='customer_mobile',
        ),
        migrations.RemoveField(
            model_name='dmtrecipient',
            name='is_bank_verified',
        ),
        migrations.RemoveField(
            model_name='dmtrecipient',
            name='verification_fee',
        ),
    ]
