# Generated by Django 5.2.7 on 2026-03-13 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0009_operatorcommission_max_commission_value'),
        ('dmt', '0004_alter_dmtrecipient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmtchargescheme',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_charge_schemes', to='commission.commissionplan'),
        ),
        migrations.DeleteModel(
            name='DMTPlan',
        ),
    ]
