# Generated by Django 5.2.7 on 2025-12-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0004_remove_dmttransaction_wallet_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMTPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('basic', 'Basic')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EKOChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_fee_net_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eko_pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_after_tds', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['amount_from'],
            },
        ),
        migrations.CreateModel(
            name='DMTChargeScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_range', models.CharField(max_length=50)),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eko_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount'), ('both', 'Both Percentage and Flat')], default='percentage', max_length=20)),
                ('percentage_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flat_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('retailer_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dealer_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('master_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('admin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('superadmin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_schemes', to='dmt.dmtplan')),
            ],
            options={
                'ordering': ['amount_from'],
            },
        ),
        migrations.CreateModel(
            name='DMTTransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eko_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superadmin_extra_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retailer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superadmin_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmt.dmtchargescheme')),
                ('dmt_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_details', to='dmt.dmttransaction')),
            ],
        ),
    ]
