# Generated by Django 5.2.7 on 2025-12-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0005_dmtplan_ekochargeconfig_dmtchargescheme_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dmtchargescheme',
            unique_together={('plan', 'amount_from', 'amount_to')},
        ),
    ]
