# Generated by Django 5.2.7 on 2026-06-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0005_alter_dmtchargescheme_plan_delete_dmtplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMTAmountRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dmtservicecharge',
            name='amount_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmt.dmtamountrange'),
        ),
    ]
