# Generated by Django 5.2.7 on 2026-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0006_dmtamountrange_alter_dmtservicecharge_amount_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmtservicecharge',
            name='amount_range',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
