# Generated by Django 5.2.7 on 2026-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt', '0007_alter_dmtservicecharge_amount_range'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DMTAmountRange',
        ),
        migrations.AlterField(
            model_name='dmtservicecharge',
            name='amount_range',
            field=models.CharField(choices=[('0-1000', '₹0 - ₹1,000'), ('1001-10000', '₹1,001 - ₹10,000'), ('10001-25000', '₹10,001 - ₹25,000'), ('25001-50000', '₹25,001 - ₹50,000'), ('50001-100000', '₹50,001 - ₹1,00,000')], max_length=20, unique=True),
        ),
    ]
