# Generated by Django 5.2.7 on 2025-12-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AEPSMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=20, unique=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pan_number', models.CharField(max_length=10)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AEPSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eko_tid', models.CharField(max_length=50, unique=True)),
                ('client_ref_id', models.CharField(max_length=50, unique=True)),
                ('bank_rrn', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=50, null=True)),
                ('initiator_id', models.CharField(max_length=15)),
                ('customer_aadhaar', models.CharField(max_length=12)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_type', models.CharField(choices=[('cash_withdrawal', 'Cash Withdrawal'), ('balance_enquiry', 'Balance Enquiry'), ('mini_statement', 'Mini Statement'), ('cash_deposit', 'Cash Deposit'), ('aadhaar_pay', 'Aadhaar Pay'), ('imps', 'IMPS')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_identifier', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='initiated', max_length=20)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='aeps.aepsmerchant')),
            ],
        ),
    ]
