# Generated by Django 5.2.7 on 2025-12-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aepsmerchant',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='aepsmerchant',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='aepsmerchant',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='aepsmerchant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aepsmerchant',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='AEPSTransaction',
        ),
    ]
