# Generated by Django 5.2.7 on 2025-12-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bbpsServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_range', models.CharField(choices=[('0-100', '₹0 - ₹100'), ('101-500', '₹101 - ₹500'), ('501-1000', '₹501 - ₹1,000'), ('1001-5000', '₹1,001 - ₹5,000'), ('5001-10000', '₹5,001 - ₹10,000')], max_length=20, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=50, unique=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('operator_type', models.CharField(choices=[('prepaid', 'Mobile Prepaid'), ('postpaid', 'Mobile Postpaid'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('landline', 'Landline'), ('tax', 'Tax'), ('credit', 'Credit Card'), ('society', 'Housing Society'), ('ott', 'OTT Subscription'), ('education', 'Education Fees'), ('municipal_tax', 'Municipal Tax'), ('clubs', 'Clubs & Associations'), ('cable', 'Cable TV'), ('lpg', 'LPG Cylinder'), ('hospital', 'Hospital'), ('insurance', 'Insurance'), ('loan', 'Loan EMI'), ('fastag', 'FASTag'), ('municipal_services', 'Municipal Services'), ('subscription_2', 'Subscription 2')], max_length=20)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flat_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['operator_name'],
                'indexes': [models.Index(fields=['operator_type', 'is_active'], name='bbps_operat_operato_125658_idx'), models.Index(fields=['circle'], name='bbps_operat_circle_356115_idx')],
            },
        ),
        migrations.CreateModel(
            name='bbpsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('operator_id', models.CharField(max_length=50)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_type', models.CharField(choices=[('prepaid', 'Mobile Prepaid'), ('postpaid', 'Mobile Postpaid'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('landline', 'Landline'), ('tax', 'Tax'), ('credit', 'Credit Card'), ('society', 'Housing Society'), ('ott', 'OTT Subscription'), ('education', 'Education Fees'), ('municipal_tax', 'Municipal Tax'), ('clubs', 'Clubs & Associations'), ('cable', 'Cable TV'), ('lpg', 'LPG Cylinder'), ('hospital', 'Hospital'), ('insurance', 'Insurance'), ('loan', 'Loan EMI'), ('fastag', 'FASTag'), ('municipal_services', 'Municipal Services'), ('subscription_2', 'Subscription 2')], default='prepaid', max_length=20)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('consumer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_ref_id', models.CharField(max_length=100)),
                ('eko_transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_message', models.TextField(blank=True, null=True)),
                ('eko_txstatus_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_response_status', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='initiated', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_request', models.JSONField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('is_plan_bbps', models.BooleanField(default=False)),
                ('plan_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbps_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='bbps_bbpstr_transac_bbfa53_idx'), models.Index(fields=['user', 'initiated_at'], name='bbps_bbpstr_user_id_faa910_idx'), models.Index(fields=['mobile_number'], name='bbps_bbpstr_mobile__5bceca_idx'), models.Index(fields=['status', 'initiated_at'], name='bbps_bbpstr_status_94fca5_idx'), models.Index(fields=['payment_status'], name='bbps_bbpstr_payment_5797c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(blank=True, max_length=100, null=True)),
                ('data_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('talktime', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_type', models.CharField(choices=[('data', 'Data Plan'), ('combo', 'Combo Plan'), ('voice', 'Voice Plan'), ('topup', 'Top-up'), ('special', 'Special bbps'), ('dth', 'DTH Plan')], default='combo', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('eko_plan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_plan_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='bbps.operator')),
            ],
            options={
                'ordering': ['amount'],
                'indexes': [models.Index(fields=['operator', 'is_active'], name='bbps_plan_operato_9d658a_idx'), models.Index(fields=['amount', 'is_active'], name='bbps_plan_amount_1ed7b0_idx')],
            },
        ),
    ]
