# Generated by Django 5.2.7 on 2025-12-30 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbps_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['operator_type', 'is_active'], name='bbps_operat_operato_125658_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['circle'], name='bbps_operat_circle_356115_idx'),
        ),
        migrations.AddField(
            model_name='plan',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='bbps.operator'),
        ),
        migrations.AddIndex(
            model_name='bbpstransaction',
            index=models.Index(fields=['transaction_id'], name='bbps_bbpstr_transac_bbfa53_idx'),
        ),
        migrations.AddIndex(
            model_name='bbpstransaction',
            index=models.Index(fields=['user', 'initiated_at'], name='bbps_bbpstr_user_id_faa910_idx'),
        ),
        migrations.AddIndex(
            model_name='bbpstransaction',
            index=models.Index(fields=['mobile_number'], name='bbps_bbpstr_mobile__5bceca_idx'),
        ),
        migrations.AddIndex(
            model_name='bbpstransaction',
            index=models.Index(fields=['status', 'initiated_at'], name='bbps_bbpstr_status_94fca5_idx'),
        ),
        migrations.AddIndex(
            model_name='bbpstransaction',
            index=models.Index(fields=['payment_status'], name='bbps_bbpstr_payment_5797c0_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['operator', 'is_active'], name='bbps_plan_operato_9d658a_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['amount', 'is_active'], name='bbps_plan_amount_1ed7b0_idx'),
        ),
    ]
