# Generated by Django 5.2.7 on 2026-02-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbps', '0002_initial'),
        ('users', '0017_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpstransaction',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbps_transaction', to='users.transaction'),
        ),
    ]
