# Generated by Django 5.2.7 on 2025-12-30 05:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_mobile', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_mobile', models.CharField(max_length=15)),
                ('recipient_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=255)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_bank_verified', models.BooleanField(default=False)),
                ('verification_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_fee', models.DecimalField(decimal_places=2, default=2.9, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vendor_mobile', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eko_tid', models.CharField(blank=True, max_length=50, null=True)),
                ('client_ref_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(max_length=50)),
                ('recipient_ifsc', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=7.0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=1.26, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=8.26, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=50, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(default='Vendor Payment', max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(default='AUTO', max_length=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_receipt_generated', models.BooleanField(default=False)),
                ('receipt_generated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='vendorpayme_user_id_889f30_idx'), models.Index(fields=['status', 'created_at'], name='vendorpayme_status_3e33e9_idx'), models.Index(fields=['client_ref_id'], name='vendorpayme_client__3b098e_idx')],
            },
        ),
    ]
