# Generated by Django 5.2.7 on 2025-12-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eko_tid', models.CharField(blank=True, max_length=50, null=True)),
                ('client_ref_id', models.CharField(max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(max_length=50)),
                ('recipient_ifsc', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
