# Generated by Django 5.2.7 on 2025-12-09 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpayment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=1.26, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='is_receipt_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_mode',
            field=models.CharField(default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='purpose',
            field=models.CharField(default='Vendor Payment', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='total_deduction',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=8.26, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='utr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='client_ref_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['user', 'created_at'], name='vendorpayme_user_id_889f30_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['status', 'created_at'], name='vendorpayme_status_3e33e9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['client_ref_id'], name='vendorpayme_client__3b098e_idx'),
        ),
    ]
