# Generated by Django 5.2.7 on 2026-01-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpayment', '0002_vendorotp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorotp',
            name='user',
        ),
    ]
