# Generated by Django 5.2.7 on 2025-12-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpayment', '0003_vendorotp_vendorbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbank',
            name='beneficiary_fee',
            field=models.DecimalField(decimal_places=2, default=2.9, max_digits=100),
        ),
    ]
