# Generated by Django 5.2.7 on 2026-01-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpayment', '0003_remove_vendorotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorotp',
            name='vendor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
