# Generated by Django 5.2.7 on 2026-02-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_refundrequest_admin_note_refundrequest_processed_at'),
        ('vendorpayment', '0004_vendorotp_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payment', to='users.transaction'),
        ),
    ]
