# Generated by Django 5.2.7 on 2026-02-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpayment', '0005_vendorpayment_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded')], default='initiated', max_length=20),
        ),
    ]
